import Head from "next/head";
import Layout from "@/layout/layout";
import { Box } from "@mui/material";
import { Content, Hero, Sidebar } from "@/components";
import { BlogsService } from "@/services/blog.service";

export default function Home({ blogs, latestBlogs, categories }) {
  console.log(blogs);

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Box>
        <Hero blogs={blogs.slice(0, 3)} />
        <Box
          sx={{
            display: "flex",
            gap: "20px",
            flexDirection: { xs: "column", md: "row" },
            padding: "20px",
          }}
        >
          <Sidebar latestBlogs={latestBlogs} categories={categories} />
          <Content blogs={blogs} />
        </Box>
      </Box>
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const blogs = await BlogsService.getAllBlogs();
  const latestBlogs = await BlogsService.getLatestBlog();
  const categories = await BlogsService.getCategories();
  console.log(latestBlogs);
  return {
    props: {
      blogs,
      latestBlogs,
      categories,
    },
  };
};
